name: build

on:
  push:
    branches: [ develop ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup .NET Core 5.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore packages.
      run: dotnet restore
    - name: Build all projects.
      run: dotnet build --configuration Release --no-restore
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/SRTM/
    - name: Nuget push
      run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/itiner/index.json
      working-directory: ./src/